# .github/workflows/codspeed.yml
name: CodSpeed
on:
  push:
    branches:
      - "main" # or "master"
  pull_request: # required to have reports on PRs
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:
jobs:
  benchmarks:
    runs-on: ubuntu-latest
    permissions: # optional for public repositories
      contents: read
      id-token: write # for OpenID Connect authentication with CodSpeed
    steps:
      - uses: actions/checkout@v4
      - name: Setup rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@v0
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed, aoc-cli
      - name: Download available input files
        env:
          ADVENT_OF_CODE_SESSION: ${{ secrets.AOC_SESSION }}
        run: |
          mkdir -p inputs
          mkdir -p inputs/2025
          for i in {1..12}; do
            aoc download -I -i inputs/2025/day$i.txt --year 2025 -d $i || true
          done
      - name: Build the benchmark target(s)
        run: cargo codspeed build
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: cargo codspeed run
